### ISSUE TITLE
 bp.getPurchaseTransactionDetails("premium_id") returns null for item thats just purchased 

### ISSUE THREAD

**Issue by deanezra** [anjlab/android-inapp-billing-v3#117]
I maybe doing something wrong here, but I successfully get a call of 'onProductPurchased()' and Google play shows I bought the in app purchase.

However, I can't ever check that the product was purchased on future app runs.

For example, I do the restorePurchases call, which fires the following onPurchaseHistoryRestored() method... But the 'premiumTransactionDetails' returned is always null!

```
@Override
    public void onPurchaseHistoryRestored() {
        /*
         * Called when purchase history was restored and the list of all owned PRODUCT ID's
         * was loaded from Google Play
         */

        // Check whether 'premium_id' has previously been purchased:
        TransactionDetails premiumTransactionDetails = bp.getPurchaseTransactionDetails("premium_id");

        if (premiumTransactionDetails == null) {
            Log.i(TAG, "onPurchaseHistoryRestored(): Havn't bought premium yet.");
            purchasePremiumButton.setEnabled(true);
        }
        else {
            Log.i(TAG, "onPurchaseHistoryRestored(): Already purchases premium.");

            purchasePremiumButton.setText(getString(R.string.you_have_premium));
            purchasePremiumButton.setEnabled(false);
            statusTextView.setVisibility(View.INVISIBLE);
        }
    }
```
How do I check what user has purchased?

Im using Android lollipop on real device (OPO) and app is in Alpha test mode.

**Comment by serggl** [comment]
@deanezra  do you check for a correct `product_id`?

**Comment by deanezra** [comment]
@serggl I switched to using the Google billing api directly after I couldn't get past the null. so I don't have the old code to check anymore.

thanls for coming back to me though.

**Comment by lateplate** [comment]
Hello. Curious if this issue was ever fully replicated? I _think_ it could be local cache related, but I'll need to dig deeper.

The scenario where it works is if you purchase on the same device and restore.

Where I'm having trouble similar to the original poster is purchasing a product on one device, and using the same Google account, attempting to restore the purchase on a separate device. I think perhaps the cache on device 2 is not updated?

Any pointers would be appreciated! Code wise, I have effectively the same thing as the original poster above.

Thanks!

**Comment by deanezra** [comment]
@lateplate, no I didn't resolve it, I switched to Google direct api to handle my in app purchasing

**Comment by lateplate** [comment]
@deanezra Thanks, appreciate the update.

This looks like it's a Google "issue". I was testing by purchasing on one device, then immediately trying to restore on the other.

Play Services doesn't appear to sync right away, as briefly discussed [here](http://stackoverflow.com/questions/18306263/android-in-app-purchases-not-syncing-immediately-across-multiple-devices). So device 2 doesn't necessarily know about the purchase yet.

While restarting device 2 didn't do anything for me, clearing Play Store's cache did the trick. Once I did that, restore worked right away.

While you wouldn't want a customer to have to do that, it's proof that the issue is not with this library's code. Google just appears to need some time to sync up purchases.

It's a fair scenario. It's probably not often that someone buys something in app, then immediately picks up a second device to restore its purchases.
