### ISSUE TITLE
Using the library from other threads?

### ISSUE THREAD

**Issue by cjserio** [anjlab/android-inapp-billing-v3#120]
Just wondering what the library's policy is on using it from a worker thread. I'm writing an OpenGL app that does 99% of it's work in JNI on a different thread. Is it safe to call the billing library from that thread or should I assume that all calls need to be dispatched to the main activity thread? Thanks!

**Comment by inktomi** [comment]
Because the flow calls through to startIntentSenderForResult, I feel like you should make sure to call purchase from the UI thread as the library is written right now. It calls activity.startIntentSenderForResult on the thread that it's running in, and that thread therefore needs to be the UI thread.
