### ISSUE TITLE
Consume purchase not working

### ISSUE THREAD

**Issue by NelzkieCoder** [anjlab/android-inapp-billing-v3#352]
I was doing a test on consume purchase however no pop up is showing up. If I use purchase() it is working. Is this a bug?

**Comment by ja2375** [comment]
It is not a bug. If you use `purchase()` and actually purchase something in the app, the popup will not show again. This is normal behaviour in order to prevent users from buying something again and again. If you want to repeat the purchase, you have to consume it first by calling `consumePurchase(productId)`.
It is explained in the README file.

**Comment by NelzkieCoder** [comment]
Got it. Thanks.. Here is what I did. So far it is working on test

```
 bp?.consumePurchase(PRODUCT_ID_TEST)
 bp?.purchase(this,PRODUCT_ID_TEST)
```
