### ISSUE TITLE
Activity Result Fragment Index Out Of range

### ISSUE THREAD

**Issue by zenyagami** [anjlab/android-inapp-billing-v3#36]
Im using in a Fragment, and i get this error Activity Result Fragment Index Out Of range so in success purchase does not trigger, if the user "click" again it triggers but not after "buying"

**Comment by ffallah** [comment]
I found the solution for this issue, the problem is that after completing the payment. the onActivityResult in MainActivity is called, not the the onActivityResult in Fragment.
In order to resolve this issue, you should call the onActivityResult in Fragment manually.
Add the following code to your MainActivity and replace "pref_fragment" with your own fragment id.
```java
@Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        Fragment fragment = getFragmentManager().findFragmentById(R.id.pref_fragment);
        fragment.onActivityResult(requestCode, resultCode, data);
    }
```
It will resolve the issue.
