### ISSUE TITLE
First time not getting any call back after purchsing product. and while purchasing second time its showing ALREADY_OWNED

### ISSUE THREAD

**Issue by ghost** [anjlab/android-inapp-billing-v3#48]
Hi,
This library is very helpful to me. Thanks :+1: 

But i am facing one issue. Purchase dialog is  showing with correct products and price and all.
After buying product m nt getting callback in (i m following the same code which u have submitted callback in IBillingHandler at the time of creating instance of the BillingProcessor)
(1)At first time when user is purchasing product 
int response = bundle.getInt(Constants.RESPONSE_CODE); in billing processor responce  = BILLING_RESPONSE_RESULT_OK & invoking startIntentSenderForResult but m not getting any callback like IBillingHandler#onProductPurchased or IBillingHandler#onBillingError
(2)And Second time if user try to purchase same product its showing  ALREADY OWN

So what can be the issue from my side that its not giving callback at first attempt ..
Thanks

**Comment by ffallah** [comment]
I found the solution for this issue, the problem is that after completing the payment. the onActivityResult in MainActivity is called, not the the onActivityResult in Fragment.
In order to resolve this issue, you should call the onActivityResult in Fragment manually.
Add the following code to your MainActivity and replace "pref_fragment" with your own fragment id.
```java
@Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        Fragment fragment = getFragmentManager().findFragmentById(R.id.pref_fragment);
        fragment.onActivityResult(requestCode, resultCode, data);
    }
```
It will resolve the issue.
