### ISSUE TITLE
Developer payload

### ISSUE THREAD

**Issue by mseroczynski** [anjlab/android-inapp-billing-v3#59]
How to set developerPayload with your library? It's very important security feature but i can't find the way to use it in README, is it missing from your library?

**Comment by dfcarvalho** [comment]
Hi,

I'm not the developer, but I think the library does that automatically.
Take a look at the source code for the BillingProcessor.purchase() method.
It seems to set a "random" payload for each purchase and check for ir when Google Play returns with a method called BillingProcessor.verifyPurchaseSignature().
I think that's what you meant.

**Comment by mseroczynski** [comment]
Thanks @dfcarvalho. Yeah, i saw it but what i want to do is use developerPayload to identify if user logged in my app should get premium status. I thought that i can manage that through one google play account purchasing item_example few times with few other developerPayloads (one per my-app-account). What do You think about it, is it possible?

**Comment by dfcarvalho** [comment]
So... your app has its own account system (it doesn't use Google Accounts for authentication) and you don't want multiple app users using the same Google Account to get Premium Status by purchasing it only once for all app users. Correct?

If that's what you mean, I'm not sure how to do it. I'm trying to solve the same problem myself for my own app.
Your idea to use developerPayload is interesting. The only problem I see with that is that you wouldn't be able to use Subscriptions (which is what I use in my app) because the same Google User wouldn't be able to purchase the same subscription more than once (or i don't think they can anyway).
If you use Managed Products instead, it might be possible, but not with this library I don't think.

You could download the source code and alter it to make this possible. I suppose all you'd need to do is to change the purchase methods so that they'd take an extra argument (the payload) so you could set the developer payload for each purchase. And then change the savePurchasePayload() and getPurchasePayload() methods so they'd also take an argument that could identify the user account associated with that payload. You could even upload your code and make a pull request to share this feature with everyone else :-)

I didn't study the source code hard enough to be sure that's really all you need, but it would probably be easier that implementing the whole In-App Billing from scratch.

**Comment by serggl** [comment]
Guys,

thats a weird use case from my point of view. I guess you need to fork this project and modify it for your needs, its quite easy. Like @dfcarvalho said, you need to only modify `purchase` method, and you already has an access to developer payload through `getPurchaseTransactionDetails`
