### ISSUE TITLE
onProductPurchased never called

### ISSUE THREAD

**Issue by zenyagami** [anjlab/android-inapp-billing-v3#86]
Im using  bp = new BillingProcessor(this, Utils.IAP_KEY,this); and
  @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        Log.v("onActivityResult");
        if (!bp.handleActivityResult(requestCode, resultCode, data))
            super.onActivityResult(requestCode, resultCode, data);
    }
the purchase its correct but in the logcat i saw the "erorr code 102" so im not sure why, if i click again the button onProductPurchased  its called correctly but not when onActivityResult returns

**Comment by dmalis** [comment]
Maybe this is related.

Upgraded to the latest jar and now I'm getting error=102 whenever I try to subscribe user with 
success = bp.subscribe(context, MyConstants.SKU_PRO_SUB_MONTHLY_099);

LOGCAT:
E/iabv3(7260): Payload mismatch: subs:a74f5037-d818-4348-80ad-66a7f4cf8031 != subs:c8734fff-dc80-4596-85da-ec89d27ec8b5

Purchases are working just fine.

**Comment by dmalis** [comment]
Additional info:

I tried to create a sucbscription 3 times: subscribe -> fails with payload mismatch -> cancel subscription in Play Store -> loop

subs:3cdcb80d-58fb-4af1-83c3-aff39019fc66 != subs:c8734fff-dc80-4596-85da-ec89d27ec8b5
subs:b94620e0-db9b-4795-bc73-176c88bd727b != subs:c8734fff-dc80-4596-85da-ec89d27ec8b5
subs:fd4a22c4-a26e-4a93-8a58-b48fe2657952 != subs:c8734fff-dc80-4596-85da-ec89d27ec8b5

developerPayload (subs:c8734fff-dc80-4596-85da-ec89d27ec8b5) param never changes.

**Comment by dmalis** [comment]
Oh well, got it.

Google is returning always the same developerPayload because of canceled transaction still being "active". So, when first in a row subscription was created it was equiped with devPayload="foo", then it was cancelled but still remained active until expiration date came.

So, because I tried to create 2nd with devPaylod="bar" after 1st was cancelled, google returned devPayload="foo" because of 1st being still active (even though cancelled).

Just wanted to clarify my issue.

**Comment by ericlw** [comment]
Is there a solution to this? Perhaps cache the old subscription in another part of the app for a day? How long does the old subscription stay 'active' for a test user, and how can I intercept the mismatched payload subscription id if I wanted

**Comment by serggl** [comment]
I guess @dmalis has provided a good explanation
