### ISSUE TITLE
Issue with Android 5.0

### ISSUE THREAD

**Issue by fidev2014** [anjlab/android-inapp-billing-v3#89]
I have some issues with in app purchases with Android 5.0, can anyone help me? 
I manage 2 subscriptions in my app, subscriptions in android version < 5 works fine in all cases, but in Android 5 > in some cases dont return the current subscriptions purchases.

**Comment by matteberna** [comment]
well, can you be a bit more specific?

**Comment by wingoku** [comment]
Did you solve the issues?

**Comment by dfcarvalho** [comment]
I don't know if its related, but I have a similar problem.
The library seems to be caching the purchases and not updating them.
But it seems it only happens on Android 5.0+

I tested it on 4.4.4 and it works fine there.
But in 5.0 purchases aren't being updated at all when you call BillingProcssor.listOwnedSubscriptions()

**Comment by dfcarvalho** [comment]
I found out what my problem was. Library is working fine. I'm the one who messed up. For some reason, I had assumed that the list of subscriptions returned by listOwnedSubscriptions() was ordered by purchase date but it's not. 

Looking into the method code, BillingProcessor stores the subscriptions as a Set (which guarantees no order) and listOwnedSubscriptions() just constructs an ArrayList from that Set without ordering the items. Coincidentally (or not, I don't know how Java's Set is implemented), in all my tests running on Android 4.4.4 the subscriptions were being listed with the newest purchase first, while on Android 5.0 they came the other way around. My app was breaking the list iteration on the first purchase of a certain type and, in Android 5.0, was never getting to the newest purchases. That's why I thought loadOwnedPurchasesFromGoogle() wasn't updating the subscriptions.
