### ISSUE TITLE
Failed to load SKU

### ISSUE THREAD

**Issue by frayela** [anjlab/android-inapp-billing-v3#92]
I am trying to test but I got no luck to load the product from my In-App Products list.

Do I really need to put the complete package name in PRODUCT_ID value?

I try to debug the value of SkyDetails but I am getting null.

Can please help. Thanks.

**Comment by albemala** [comment]
Could you show some code about what you are doing that is not working?

Also, in order to have In-App Billing working, follow these steps:

 - Add `<uses-permission android:name="com.android.vending.BILLING" />` permission to the **AndroidManifest.xml** .
 - Create a signed APK and upload it to the developer console, as alpha, beta or production.
 - Publish the APK or [create a google group and add an alpha list of testers](https://support.google.com/googleplay/android-developer/answer/3131213?hl=en).
 - **You have to wait some hours in order to see the in-app purchases in your app**

**Comment by serggl** [comment]
@albemala explanation seems correct, thats how it should be accomplished.
Closing due inactivity
